# Generated by Django 5.2.1 on 2025-05-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True, verbose_name='Термин')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
