# Generated by Django 5.2.1 on 2025-05-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_vacancy_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('master', 'Мастер'), ('client', 'Клиент')], default='Мастер', max_length=10),
        ),
    ]
