# Generated by Django 5.2.1 on 2025-05-15 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MinValueValidator(18)),
        ),
    ]
