# Generated by Django 5.2.1 on 2025-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('master', 'Мастер'), ('client', 'Клиент')], default='master', max_length=10),
        ),
    ]
