# Generated by Django 5.2.1 on 2025-05-15 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parts',
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.part')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.service')),
            ],
            options={
                'unique_together': {('service', 'part')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='parts',
            field=models.ManyToManyField(through='cars.ServicePart', to='cars.part'),
        ),
        migrations.DeleteModel(
            name='OrderPart',
        ),
    ]
