# Generated by Django 5.2.1 on 2025-05-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_cartype_created_at_cartype_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
