# Generated by Django 5.2.1 on 2025-05-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.service', verbose_name='Услуга'),
        ),
    ]
