# Generated by Django 5.2.1 on 2025-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_promocode_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='profiles/'),
        ),
    ]
